services:
  controller:
    image: alpine:latest
    command: echo "Ich bin der controller" && sleep 5

  poller:
    image: alpine:latest
    command: echo "Ich bin der poller" && sleep 5

  gateway:
    image: alpine:latest
    command: echo "Ich bin das gateway" && sleep 5

  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - db:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=83c06345362b09d504b279464923117896aa6f57ed6c24e48a3b56fb1d3cdb04

  telegraf:
    image: telegraf:latest
    restart: unless-stopped
    volumes:
      - ./config/telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
      - mqtt-broker

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influxdb

  mqtt-broker:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config/mosquitto/config:/mosquitto/config

volumes:
  db:
  grafana:
