services:
  com-twin:
    build: ./com-twin/

  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - db:/var/lib/influxdb
    env_file:
      - .env

  telegraf:
    image: telegraf:latest
    restart: unless-stopped
    volumes:
      - ./config/telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
      - mqtt-broker
    env_file:
      - .env

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influxdb

  mqtt-broker:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config/mosquitto/config:/mosquitto/config

volumes:
  db:
  grafana:
