{
 "title": "Tjarks Home",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "CURRENT_POWERMETER", "query": "2370" },
   {
    "name": "aggregation",
    "query": "1s,10s,1m,15m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Energy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "${Energy L1} + ${Energy L2} + ${Energy L3} + (((${CURRENT_POWERMETER} - 1300) * 1000) - (${Energy L1} + ${Energy L2} + ${Energy L3}))",
     "type": "math"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shelly-em3-meter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"0\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"emeter\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"5835dfc83ddb\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()"
    },
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shelly-em3-meter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"emeter\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"5835dfc83ddb\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()"
    },
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shelly-em3-meter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"2\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"emeter\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"5835dfc83ddb\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Current Power",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "${Current Power L1} + ${Current Power L2} + ${Current Power L3}",
     "type": "math"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shelly-em3-meter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"0\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"emeter\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"5835dfc83ddb\")\r\n  |> aggregateWindow(every: ${aggregation}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shelly-em3-meter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"emeter\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"5835dfc83ddb\")\r\n  |> aggregateWindow(every: ${aggregation}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"my-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shelly-em3-meter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"2\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"emeter\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"5835dfc83ddb\")\r\n  |> aggregateWindow(every: ${aggregation}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "expression": "${Power L1} + ${Power L2} + ${Power L3}",
     "type": "math"
    }
   ]
  }
 ]
}